### ISSUE TITLE
[Question] Parallel running

### ISSUE THREAD

**Issue by youpengzhao** [PKU-MARL/omnisafe#110]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

I have completed the installation of omnisafe and successfully run the example code. To make the experiment faster, I try to adjust the ''parallel'' parameter, I find that the program can run when parallel=2, which is shown below:
![df8978a39c84249f0a39418df7195d0](https://user-images.githubusercontent.com/48088351/217718271-dd3fb6b8-dd25-46fa-8080-845014949819.png)
However, when this parameter is set ≥3, it seems that the code can not be executed. The error is shown below:
![a5ed431bd5a67be40c2dee2da01c49e](https://user-images.githubusercontent.com/48088351/217718413-1ddf3e91-f846-44fc-bcd6-1a7ac386705b.png)

Maybe this problem is caused by that my device does not have enough cores to use, but I'm not sure. In this way, I put forward this problem and hope the developers can check the reason of this issue.

**Comment by Gaiejj** [comment]
There is an assert check on line 68 of `policy_gradient.py`:
`assert self.cfgs.steps_per_epoch % distributed_utils.num_procs() == 0`.
That means the number of processes `distributed_utils.num_procs()` must be a divisor of the number of steps per epoch `self.cfgs.steps_per_epoch`.
You only need to modify any of these two parameters to make it meet this requirement。
e.g. `python train_policy.py --algo PPOLag --env-id SafetyPointGoal1-v0 --parallel 4`

**Comment by youpengzhao** [comment]
I see, thank you very much.
