### ISSUE TITLE
[Question] Having trouble in replicating  the performance of PPO-Lag

### ISSUE THREAD

**Issue by zhouzhiqian** [PKU-MARL/omnisafe#114]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

I trained a policy with PPO-Lag yesterday, and  got a terrible result. The learned policy barely  navigate the robot to the given goal. After 300 epoches, the EpRet/Mean is nearly zero and the EpCost/Mean is still over 25.0, the given limitation on epcost. I used the given default parameters of PPO-Lag and started the training process in the terminal with the command of "python train_policy.py --env-id SafetyPointGoal1-v0 --algo PPOLag --parallel 4". The whole training process can be found in the following figure. 
![PPO-Lag](https://user-images.githubusercontent.com/29911737/217986202-ac80eeec-820f-4811-b3b8-54b55153a7fa.png)

Besides, a similar situation has emerged in several other algorithms, including CPO, IPO, RCPO, and CUP.

Thanks for your reading and help.

**Comment by Gaiejj** [comment]
Thank you very much for your comments. We also found this bug, and in [PR #113](https://github.com/PKU-MARL/omnisafe/pull/113) we fix it. 

<img width="858" alt="image" src="https://user-images.githubusercontent.com/108712610/218067347-21662272-9ebc-469f-a0de-c78d714cc2e2.png">

At the same time, we use `python train_policy.py --algo PPOLag --env-id SafetyHumanoidVelocity-v4` to test, the effect is shown in the figure below, basically in line with expectations.

If you encounter similar problems in subsequent use, please contact us in time. Thanks again for your comments.

**Comment by zhouzhiqian** [comment]
From your code, PR #113 seems only fix some typo bugs and argument bugs, which may be not helpful in this issue. According to my experimental results, PR#112 (change the actor type from gaussian_std_net to gaussian)is more important to deal with our reported training bug.  
![ppo-lag-pr112](https://user-images.githubusercontent.com/29911737/218627542-97f47182-7e97-4edb-b763-fb63f9d9bf3f.png)

**Comment by Gaiejj** [comment]
You are a very caring person. Thanks for your comments. Using `gaussian` in PPO does perform better than `gaussian_std_net`.
