### ISSUE TITLE
[Question] Why you use the raw action in off-policy algorithms to update actor-critic

### ISSUE THREAD

**Issue by hdadong** [PKU-MARL/omnisafe#120]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

 Why you use the raw action in off-policy algorithms to update actor-critic?
Shouldn't it be updated using the action after scaling?
https://github.com/PKU-MARL/omnisafe/blob/main/omnisafe/algorithms/off_policy/sac.py#L91

**Comment by Gaiejj** [comment]
Thanks for your question. in experiment we actually found that using `action` instead of `raw_action` is better. We fixed this in PR #119. If you find other problems in future use, please contact us any time you want. Thanks again !
