### ISSUE TITLE
[Question] How good is CPO on point goal.

### ISSUE THREAD

**Issue by YUYING07** [PKU-MARL/omnisafe#130]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

![Figure_1](https://user-images.githubusercontent.com/53050641/222890361-c5b3760d-40f6-430e-a4eb-ba0def5efcd0.png)

Hi, I have ran CPO on PointGoal for about 1M time step.
The return is only 20 and cost is 40-50.

However, a good policy on pointgoal should be return=80 and cost = 2-3, is that normal?

**Comment by YUYING07** [comment]
![Figure_1](https://user-images.githubusercontent.com/53050641/222895286-caf07e4b-4c69-4b71-bef1-b1c0a129374b.png)

**Comment by Gaiejj** [comment]
Your questions are welcome. In fact, on the ``SafetyPointGoal1`` task, the return value can only reach a maximum of ``25-27``, while the cost oscillates around the set ``cost_limit=25``. The first picture below is the official effect of ``Safety-Gym``, and the latter picture is The effect of OmniSafe.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/108712610/222916866-d2210719-3a4f-4005-a304-1df5963dfeb6.png">
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/108712610/222916884-492cacaf-9a13-4877-a12b-6a9dc5e1121d.png">
Thank you for your comments, and you are welcome to continue to contact us in subsequent use.

**Comment by YUYING07** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已经收到您的邮件~欢迎下次再邮~

**Comment by zmsn-2077** [comment]
Feel free to ask to reopen this if you have more questions.
