### ISSUE TITLE
[Question] how can I run agent in omnisafe but using safety_gymnasium env

### ISSUE THREAD

**Issue by zlpiscoming** [PKU-MARL/omnisafe#132]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

I want to run a omnisafe with a safety_gymnasium env or some other env, how can i train it and eval it.
`import safety_gymnasium
import omnisafe

if __name__ == '__main__':
    env = safety_gymnasium.make("SafetyCarPush2-v0")
    agent = omnisafe.Agent('PPOLag', env)
    agent.learn()
    obs, info = env.reset()
    ep_reward, ep_cost = 0, 0
    for i in range(1000):
        action, _states = agent.predict(obs, deterministic=True)
        obs, reward, cost, done, _, info = env.step(action)
        ep_reward += reward
        ep_cost += cost
        env.render()
        if done:
            print(ep_reward, ep_cost)
            obs, info = env.reset()
            ep_reward, ep_cost = 0, 0
    env.close()`

like this.

**Comment by Gaiejj** [comment]
You can run the following command line: 

```bash

cd omnisafe/exmaples
python train_policy.py --algo ALGO --env-id ENV
```

where ``ALGO`` can be algorithms in omnisafe, e.g. ``ppo``, ``trpo``, and ``ENV`` can be ``SafetyPointGoal1-v0`` and so on.

Then you can check your experiment results in ``omnisafe/examples/runs``. You can copy the path in ``examples/evaluate_saved_policy.py`` and run 

```bash
cd omnisafe/examples
python evaluate_saved_policy.py
```

to evaluate your policy.

**Comment by zlpiscoming** [comment]
can i use omnisafe agent for the env which i create myself.

**Comment by zmsn-2077** [comment]
Feel free to ask to reopen this if you have more questions.
