### ISSUE TITLE
[Question] Something wrong when I check the progress.txt

### ISSUE THREAD

**Issue by Gaiejj** [PKU-MARL/omnisafe#140]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

When I trained ``TRPO`` on ``SafetyHumanoidVelocity-v4``, I found that ``progress.txt`` recorded multiple lines of data in the same line. This makes it difficult for me to draw the training curve locally.
![image](https://user-images.githubusercontent.com/108712610/223721652-af11d783-e8c4-4a33-b5fc-567e9e227563.png)

**Comment by wfei1** [comment]
I ran into a similar problem, described in detail in issue #143 .

**Comment by wfei1** [comment]
I think the parallelism mechanism leading to the same timestamp is the source of this problem.

**Comment by Gaiejj** [comment]
Thanks! I can log the ``progress.txt`` properly now.
