### ISSUE TITLE
[BUG] the logger bug in Experiment Grid

### ISSUE THREAD

**Issue by wfei1** [PKU-MARL/omnisafe#143]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.1.0

### System information

0.1.0, linux ubuntu 20.04

### Problem description

I noticed that one of the very nice features of omnisafe is the `experiment grid`, which can run a very large number of experiments in large batches.
But I found that logger is distinguishing different experiment folders by current timestamp as a different variable, this is not a problem in case of no parallelism, but I found that in `experement grid` parallelism, different algorithms may be created at the same time.
Then there will be a potential bug of different algorithms logging to a folder at the same time, as evidenced by the following.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/118658162/224105597-979c65a1-ce72-4fcb-b3c5-b9a0b3ecc7cc.png">

<img width="631" alt="image" src="https://user-images.githubusercontent.com/118658162/224105720-0f45ed75-9eca-4895-9a88-f8daaee3e134.png">

I think this potential bug may have something to do with issue #140 as well.

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by Gaiejj** [comment]
We are sorry for that bug.

When you tune different parameters in the same algorithm on the same environment, the logger may write multiple experiments results into the same ``csv`` file. 

We have fixed it in PR #145 . Thanks for your feedback! If you encounter any other problem in further use, please feel free to open an issue !

**Comment by zmsn-2077** [comment]
Feel free to ask to reopen this if you have more questions.
