### ISSUE TITLE
[Question] Training Data Visualization with tensorboard?

### ISSUE THREAD

**Issue by wmkai** [PKU-MARL/omnisafe#23]
## Questions
I found that omnisafe records a lot of data from training, some of which are particularly useful for tuning references, but some of the recorded data I did not understand, for example,
1. `FPS,` I run `ppo` in omnisafe, in environment SafetyPointGoal1-v0, and the following graph appears. Can you please explain what FPS means?
![image](https://user-images.githubusercontent.com/39148461/204861251-c8c70c78-6ba4-4961-813b-2f5c24d5c4b8.png)

2. I ran `TRPOLag` at the same time, and I found that the tensorboard recorded the following data. What is the meaning of these losses? Is the smaller, the better?
![image](https://user-images.githubusercontent.com/39148461/204861333-26506364-5a6a-4103-8417-ef85299ae65d.png)

## Checklist

- [x] I have checked that there is no similar issue in the repo. (**required**)
- [x] I have read the [documentation](https://omnisafe.readthedocs.io). (**required**)

**Comment by zmsn-2077** [comment]
`FPS.` It stands for `step/s.` It indicates the number of interactions with the environment per second, and we visualize this metric in the middle of the process so that the user can see the model throughput in real-time and be aware of the server blockage.

**Comment by wmkai** [comment]
Thanks for your reply!
