### ISSUE TITLE
[Feature Request] Model-based algo codes need to be enhanced for code specification

### ISSUE THREAD

**Issue by zmsn-2077** [PKU-MARL/omnisafe#25]
## Motivation
We noticed that the model-base-related code is too cumbersome and the related code is duplicated, we will fix it by this weekday.

## Checklist

- [x] I have checked that there is no similar issue in the repo. (**required**)

**Comment by zmsn-2077** [comment]
This code cleaning will be postponed because the mod-based maintainer has been confirmed COVID-19.

**Comment by hdadong** [comment]
The model-based algorithms have been enhanced!
