### ISSUE TITLE
[Feature Request] More details about how to DIY users' local environments and modify default configs of environments in documentation and README.

### ISSUE THREAD

**Issue by muchvo** [PKU-MARL/omnisafe#38]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Motivation

Consider add more details about how to DIY local environments and modify default configs of environments in documentation and README.

### Additional context

Just like this in safety-gym:
![0193cc58c4f0d2b0682f81d57e28926](https://user-images.githubusercontent.com/118189931/206855484-5ccdaaa4-8d56-4cfd-9f7d-2f87b0d80de0.png)

**Comment by zmsn-2077** [comment]
These changes have been made and the issue will now be closed.
