### ISSUE TITLE
How to change the render mode?

### ISSUE THREAD

**Issue by augustcat0016** [PKU-MARL/omnisafe#4]
## Questions
It seems that the environment cannot modify its rendering mode. We tested two ways and both failed.

Like the new way in gymnasium library:
`env = safety_gymnasium.make(env_name, render='rgb_array')` 
which gets 
`TypeError: __init__() got an unexpected keyword argument 'render'`

Or the old way in gym library:
`env.render(render_mode='rgb_array')`
which gets
`TypeError: env_render_passive_checker() got an unexpected keyword argument 'render_mode'`.

## Checklist

- [x] I have checked that there is no similar issue in the repo. (**required**)
- [x] I have read the [documentation](https://omnisafe.readthedocs.io). (**required**)

**Comment by zmsn-2077** [comment]
We just added support for render mode and refactored part of the safety_gymnasium/safety_gym_v2 code in #5 ,  which is now used as follows,
```
import argparse
import safety_gymnasium


def run_random(env_name):
    env = safety_gymnasium.make(env_name, render_mode='rgb_array')
    # env.seed(0)
    obs, _ = env.reset()
    terminled = False
    ep_ret = 0
    ep_cost = 0
    while True:
        if terminled:
            print('Episode Return: %.3f \t Episode Cost: %.3f' % (ep_ret, ep_cost))
            ep_ret, ep_cost = 0, 0
            obs, _ = env.reset()
        assert env.observation_space.contains(obs)
        act = env.action_space.sample()
        assert env.action_space.contains(act)
        # Use the environment's built_in max_episode_steps
        if hasattr(env, '_max_episode_steps'):
            max_ep_len = env._max_episode_steps

        obs, reward, cost, terminled, truncated, info = env.step(act)

        ep_ret += reward
        ep_cost += cost


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--env', default='SafetyPointGoal0-v0')
    args = parser.parse_args()
    run_random(args.env)
```
then,
![image](https://user-images.githubusercontent.com/73586554/202998195-b32c7fc7-1f94-4a6c-9f0f-803067384ec8.png)
If you use `render_mode = 'human'`, then,
![image](https://user-images.githubusercontent.com/73586554/202998378-a0d59b7d-735e-4656-bab9-77787fe9794a.png)

**Comment by augustcat0016** [comment]
Thx, this improvement has helped me a lot.
