### ISSUE TITLE
[Question] Importance!!!! Do you have the performance of the CUP(NeurIPS 2022) algorithm on safety gym?

### ISSUE THREAD

**Issue by yinglinmonian** [PKU-MARL/omnisafe#46]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

I see that there is already `CUP` related code in the `dev` branch, but I can't run the algorithm at the moment, do you have the performance of the CUP algorithm on safety gym?

**Comment by zmsn-2077** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/73586554/209115613-2f82ece1-4d6b-4593-b430-293b316ba179.png">
<img width="811" alt="image" src="https://user-images.githubusercontent.com/73586554/209115646-8aef1d09-22e8-4562-9dae-9adf9fbe39a9.png">
This is how CUP performed on `Safety-PointGoal1`.

**Comment by yinglinmonian** [comment]
okok, Thanks!
