### ISSUE TITLE
[BUG] pylint: error: argument --spelling-dict

### ISSUE THREAD

**Issue by zmsn-2077** [PKU-MARL/omnisafe#85]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.0.1

### System information

3.8.15 (default, Nov 24 2022, 15:19:38)
[GCC 11.2.0] linux
0.0.1

### Problem description

When I use `pre-commit run --all-files`, the following error appears: 
```python
usage: pylint [options]
pylint: error: argument --spelling-dict: invalid choice: 'en_US' (choose from '')
```

### Reproducible example code

The Python snippets:

```python

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1.
2.
3.

**Comment by zmsn-2077** [comment]
A solution is `pip install pyenchant`; more details can refer to [stackoverflow](https://stackoverflow.com/questions/69203782/pylint-error-optparse-optionvalueerror-option-spelling-dict-invalid-value).

**Comment by XuehaiPan** [comment]
Install `pylint` with extras would resolve this.

```bash
pip3 install 'pylint[spelling]'
```
