### ISSUE TITLE
[Question] Cost Loss and Update for SAC Lagrangian

### ISSUE THREAD

**Issue by konwook** [PKU-MARL/omnisafe#87]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### Questions

1. Why does the [backup](
https://github.com/PKU-MARL/omnisafe/blob/main/omnisafe/algorithms/off_policy/sac_lag.py#L88) for the cost critic loss assign `data['rew']` instead  of `data['cost']` to `cost`? Wouldn't this update result in a cost critic identical to the standard value critic? 

2. The initial [update](https://github.com/PKU-MARL/omnisafe/blob/main/omnisafe/algorithms/off_policy/sac_lag.py#L110) for the Lagrange multiplier uses `Jc = data['cost'].sum().item()`. However, the `update_lagrange_multiplier` method uses `Jc` to compute the [lambda loss](https://github.com/PKU-MARL/omnisafe/blob/babfaac959be44ba8f84a83037bfbfd6b6f7f165/omnisafe/common/lagrange.py#L58) which has function signature: `def compute_lambda_loss(self, mean_ep_cost):` Shouldn't `Jc` be defined as `Jc = data['cost'].mean().item()` if it's the `mean_ep_cost`?

**Comment by Gaiejj** [comment]
You are very attentive and thank you very much for your suggestions. We have fixed this issue on the ``dev`` branch. If you find a new issue in subsequent use, we will fix it as soon as possible.
